SELECT DISTINCT 
CLCL.CLCL_ID AS "ID", 
CDDL.CDDL_SEQ_NO AS "Line #",
CLCL.CLCL_CL_TYPE AS "Type", 
CLCL.CLCL_CL_SUB_TYPE AS "Sub Type", 
CLCL.CLCL_RECD_DT AS "Received Date", CLCL.PDPD_ID As "Product ID", 
CLCL.CLCL_NTWK_IND AS "Network Type", CDDL.PSDC_ID AS "Place Of Service",
CDDL.DPDP_ID AS "Procedure Code", CLCL.CLCL_TOT_CHG AS "Total Charge", 
CDDL.CDDL_ALLOW AS "Allowed Amount", CLCL.CLCL_PA_PAID_AMT AS "Paid Amount"
FROM FACETS.CMC_CLCL_CLAIM CLCL
JOIN FACETS.CMC_CDDL_CL_LINE CDDL ON CDDL.CLCL_ID=CLCL.CLCL_ID
LEFT JOIN FACETS.CMC_SBSB_SUBSC SBSB ON SBSB.SBSB_CK = CLCL.SBSB_CK
LEFT JOIN FACETS.CMC_MEME_MEMBER MEME ON MEME.MEME_CK=CLCL.MEME_CK
LEFT JOIN FACETS.CMC_SGSG_SUB_GROUP SGSG ON SGSG.SGSG_CK = CLCL.SGSG_CK
LEFT JOIN FACETS.CMC_GRGR_GROUP GRGR ON GRGR.GRGR_CK=CLCL.GRGR_CK
LEFT JOIN FACETS_CUSTOM.EMBT_CLCL_CLAIM_ARCH CLAIM_ARCH ON CLCL.GRGR_CK=CLAIM_ARCH.GRGR_CK
LEFT JOIN FACETS.CMC_MATX_ACCUM_TXN MATX ON CLCL.MEME_CK = MATX.MEME_CK
LEFT JOIN FACETS.CMC_FATX_ACCUM_TXN FATX ON CLCL.MEME_CK = FATX.MEME_CK
LEFT JOIN FACETS.CMC_CDEC_LI_ENC CDEC ON CLCL.CLCL_ID = CDEC.CLCL_ID
LEFT JOIN FACETS_XC.CMC_CLED_EDI_DATA XC_CLED ON CLCL.CLCL_ID=XC_CLED.CLCL_ID
LEFT JOIN FACETS_CUSTOM.EMBT_CLED_EDI_DATA_ARCH CUSTOM_CLED ON CLCL.CLCL_ID=CUSTOM_CLED.CLCL_ID