SELECT DISTINCT
SBSB.SBSB_ID AS "Subscriber ID",
MEME.MEME_LAST_NAME AS "Last Name",MEME.MEME_FIRST_NAME AS "First Name",MEME.MEME_SFX AS "Suffix",MEME.MEME_SEX AS "Gender",MEME.MEME_BIRTH_DT AS "Date Of Birth",MEME.MEME_MARITAL_STATUS AS "Marital Status",
SBAD.SBAD_CITY AS "City" ,SBAD.SBAD_STATE AS "State",SBAD.SBAD_ZIP AS "Zip",
MEPE.MEPE_EFF_DT AS "Eff.Date",MEPE.MEPE_TERM_DT AS "Term.Date",MEPE.CSPI_ID AS "Class Plan ID",MEPE.PDPD_ID AS "Product ID",
LOBD.LOBD_ID AS "LOB ID"
FROM FACETS.CMC_SBSB_SUBSC SBSB
JOIN FACETS.CMC_SBAD_ADDR SBAD ON SBAD.SBSB_CK = SBSB.SBSB_CK 
JOIN FACETS.CMC_MEME_MEMBER MEME ON MEME.SBSB_CK=SBSB.SBSB_CK AND MEME.GRGR_CK = SBSB.GRGR_CK
JOIN FACETS.CMC_MEPE_PRCS_ELIG MEPE ON MEPE.MEME_CK=MEME.MEME_CK AND MEPE.GRGR_CK=MEME.GRGR_CK AND SYSDATE BETWEEN MEPE.MEPE_EFF_DT AND MEPE.MEPE_TERM_DT
JOIN FACETS.CMC_SGSG_SUB_GROUP SGSG ON SGSG.SGSG_CK = MEPE.SGSG_CK AND SGSG.GRGR_CK = MEPE.GRGR_CK
JOIN FACETS.CMC_GRGR_GROUP GRGR ON GRGR.GRGR_CK=MEME.GRGR_CK  
JOIN FACETS.CMC_PDPD_PRODUCT PDPD ON PDPD.PDPD_ID=MEPE.PDPD_ID
JOIN FACETS.CMC_LOBD_LINE_BUS LOBD ON LOBD.LOBD_ID=PDPD.LOBD_ID