SELECT 
SBSB.SBSB_ID,
MEME.MEME_SFX,
CONCAT(SBSB.SBSB_ID,CASE WHEN LENGTH(MEME.MEME_SFX)<2 THEN CONCAT('0',MEME.MEME_SFX) END) AS MEMBER_ID,
MEME.MEME_LAST_NAME,MEME.MEME_FIRST_NAME,MEME.MEME_MID_INIT,MEME.MEME_FAM_LINK_ID,TO_CHAR(MEME.MEME_BIRTH_DT,'YYYYMMDD') AS MEME_BIRTH_DT,
MEME_SEX, MEPE.CSPI_ID,PDPD.LOBD_ID,MEPE.MEPE_EFF_DT,MEPE.MEPE_TERM_DT,
SBAD.SBAD_ADDR1,SBAD.SBAD_ADDR2,SBAD.SBAD_ADDR3,SBAD.SBAD_CITY,SBAD.SBAD_STATE,SBAD.SBAD_ZIP
FROM FACETS.CMC_SBSB_SUBSC SBSB
JOIN FACETS.CMC_MEME_MEMBER MEME ON MEME.SBSB_CK = SBSB.SBSB_CK AND MEME.SBSB_CK =SBSB.SBSB_CK AND MEME.GRGR_CK = SBSB.GRGR_CK
JOIN FACETS.CMC_MEPE_PRCS_ELIG MEPE ON MEME.MEME_CK = MEPE.MEME_CK 
JOIN FACETS.CMC_SBAD_ADDR SBAD ON SBAD.SBSB_CK = SBSB.SBSB_CK AND SBAD.GRGR_CK = SBSB.GRGR_CK
JOIN FACETS.CMC_PDPD_PRODUCT PDPD ON MEPE.PDPD_ID=PDPD.PDPD_ID 