INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Claim ID','CLCL.CLCL_ID','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Provider Agreement ID','CLCL.AGAG_ID','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Claim Sub Type','CLCL.CLCL_CL_SUB_TYPE','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Claim Status','CLCL.CLCL_CUR_STS','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Network Indicator','CLCL.CLCL_NTWK_IND','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Claim Total Payable','CLCL.CLCL_TOT_PAYABLE','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Class Plan ID','CLCL.CSPI_ID','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Product ID','CLCL.PDPD_ID','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Servicing Provider ID','CLCL.PRPR_ID','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Disallow Explanation Code [LI]','CDML.CDML_DISALL_EXCD','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Paid Amount [LI]','CDML.CDML_PAID_AMT','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Disallowed Amount [LI]','CDML.CDML_DISALL_AMT','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Allowed Amount [LI]','CDML.CDML_ALLOW','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Deducted Amount [LI]','CDML.CDML_DED_AMT','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Coinsurance Amount [LI]','CDML.CDML_COINS_AMT','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Diagnosis Code','CDML.IDCD_ID','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Procedure Code','CDML.IPCD_ID','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('LOB ID','CDML.LOBD_ID','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Place of Service ID','CDML.PSCD_ID','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Revenue Code','CDML.RCRC_ID','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Other Carrier Reason Code','CLCB .CLCB_COB_REAS_CD','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('COB Type','CLCB .CLCB_COB_TYPE','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('EDI Claim Trading Partner','CLED.CLED_TRAD_PARTNER','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Bill Classification','CLHP.CLHP_BILL_CLASS','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Facility Type','CLHP.CLHP_FAC_TYPE','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Bill Frequency','CLHP.CLHP_FREQUENCY','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Routing Reason Description','WWMS.WRTR_REASON_DESC','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Warning Message ID','WWMS.WWMS_MESSAGE_ID','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Procedure Description','IPCD.IPCD_DESC','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Provider Specialty','PRPR.PRCF_MCTR_SPEC','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Provider Type','PRPR.PRPR_MCTR_TYPE','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Provider NPI','PRPR.PRPR_NPI','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Provider Taxonomy Code','PRPR.PRPR_TAXONOMY_CD','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Subscriber Contrived Key','SBSB.SBSB_CK','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Subscriber ID','SBSB.SBSB_ID','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Member Birth Date','TO_DATE(MEME.MEME_BIRTH_DT,\'MM/DD/YYYY\')','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Line Item Override EXCDID','CDOR.EXCD_ID','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Claim Override EXCDID','CLOR.EXCD_ID','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Alternate Payee Name','CLAP.CLAP_NAME','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Explanation Code','CDMD.EXCD_ID','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Reason Code [CDSM_OC_REAS_CD]','CDSM.CDSM_OC_REAS_CD','claim');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Subscriber Identifier','SBSB.SBSB_ID','member');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Member Suffix','MEME.MEME_SFX','member');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Member Last Name','MEME.MEME_LAST_NAME','member');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Member First Name','MEME.MEME_FIRST_NAME','member');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Member Middle Initial','MEME.MEME_MID_INIT','member');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Member Family Link ID','MEME.MEME_FAM_LINK_ID','member');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Member DOB [format=MM/DD/YYYY]','TO_DATE(MEME.MEME_BIRTH_DT,\'MM/DD/YYYY\')','member');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Member Gender [choices=m or f]','MEME_SEX','member');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Member Class Plan ID','MEPE.CSPI_ID','member');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Member Product ID','PDPD.LOBD_ID','member');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Member Elig. Effective Date [format=MM/DD/YYYY]','TO_DATE(MEPE.MEPE_EFF_DT,\'MM/DD/YYYY\')','member');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Member Elig. Termination Date [format=MM/DD/YYYY]','TO_DATE(MEPE.MEPE_TERM_DT,\'MM/DD/YYYY\')','member');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Member City','SBAD.SBAD_CITY','member');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Member State','SBAD.SBAD_STATE','member');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Member Zip','SBAD.SBAD_ZIP','member');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Member Age','TRUNC(MONTHS_BETWEEN(SYSDATE,MEME.MEME_BIRTH_DT)/12)','member');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Provider Identifier','PRPR.PRPR_ID','provider');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('National Provider ID','PRPR.PRPR_NPI','provider');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Provider Type[choices=P,F,G]','PRPR.PRPR_ENTITY','provider');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Provider Addr Term Date [format=MM/DD/YYYY]','TO_DATE(PRAD.PRAD_TERM_DT,\'MM/DD/YYYY\')','provider');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Provider Network Term Date [format=MM/DD/YYYY]','TO_DATE(NWPR.NWPR_TERM_DT,\'MM/DD/YYYY\')','provider');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Provider Term Date [format=MM/DD/YYYY]','TO_DATE(PRPR.PRPR_TERM_DT,\'MM/DD/YYYY\')','provider');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Provider Tax ID','PRPR.MCTN_ID','provider');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Provider Network ID','NWPR.NWNW_ID','provider');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Provider Taxonomy CD','PRPR.PRPR_TAXONOMY_CD','provider');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Provider MCTR Entity','MCTR.MCTR_ENTITY','provider');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Provider MCTR Description','MCTR.MCTR_DESC','provider');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Provider Name','PRPR.PRPR_NAME','provider');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Provider City','PRAD.PRAD_CITY','provider');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Provider State','PRAD.PRAD_STATE','provider');
INSERT INTO `metaxwalk`(`user_field_name`, `db_field_name`, `meta_type`) VALUES ('Provider Zip','PRAD.PRAD_ZIP','provider');

