SELECT
PRPR.PRPR_ID,PRPR.PRPR_NPI,PRPR.PRPR_ENTITY,PRAD.PRAD_TERM_DT,NWPR.NWPR_TERM_DT,PRPR.PRPR_TERM_DT,PRPR.MCTN_ID,
NWPR.NWNW_ID,PRPR.PRPR_TAXONOMY_CD,
SBSB.SBSB_ID,ELIG.MEME_CK,ELIG.PDPD_ID,MCTR.MCTR_ENTITY,MCTR.MCTR_DESC,
PRPR.PRPR_NAME,PRAD.PRAD_ADDR1,PRAD.PRAD_ADDR2,PRAD.PRAD_CITY, PRAD.PRAD_STATE,PRAD.PRAD_ZIP
FROM FACETS.CMC_SBSB_SUBSC SBSB
INNER JOIN FACETS.CMC_MEME_MEMBER MEME ON SBSB.SBSB_CK = MEME.SBSB_CK
INNER JOIN FACETS.CMC_MEPE_PRCS_ELIG ELIG ON MEME.MEME_CK = ELIG.MEME_CK
INNER JOIN FACETS.CMC_CSPI_CS_PLAN PLAN ON ELIG.CSPI_ID = PLAN.CSPI_ID
INNER JOIN FACETS.CMC_NWST_NET_SET NWST ON PLAN.NWST_PFX = NWST.NWST_PFX
INNER JOIN FACETS.CMC_NWPR_RELATION NWPR ON NWST.NWNW_ID  =  NWPR.NWNW_ID
INNER JOIN FACETS.CMC_PRPR_PROV PRPR ON NWPR.PRPR_ID = PRPR.PRPR_ID
INNER JOIN FACETS.CMC_PRAD_ADDRESS PRAD ON PRAD.PRAD_ID = PRPR.PRAD_ID 
INNER JOIN FACETS.CMC_MCTR_CD_TRANS MCTR ON MCTR.MCTR_TYPE = PRPR.PRPR_MCTR_TYPE 
WHERE SYSDATE BETWEEN ELIG.MEPE_EFF_DT AND ELIG.MEPE_TERM_DT