SELECT DISTINCT PRPR.PRPR_ID AS "ID",PRPR.PRPR_NAME AS "Name",PRPR.PRPR_ENTITY AS "Provider Type",PRPR.PRPR_NPI AS "NPI",PRPR.MCTN_ID as "Tax ID" ,PRPR.PRCF_MCTR_SPEC AS "Specialty Code",MCTR.MCTR_DESC AS "Specialty Description"
FROM FACETS.CMC_PRPR_PROV PRPR 
JOIN FACETS.CMC_PRAD_ADDRESS PRAD ON PRAD.PRAD_ID=PRPR.PRAD_ID
JOIN FACETS.CMC_MCTR_CD_TRANS MCTR ON MCTR.MCTR_ENTITY='PRAC' AND MCTR.MCTR_TYPE='SPEC' AND MCTR.MCTR_VALUE = PRPR.PRCF_MCTR_SPEC
JOIN FACETS.CMC_NWPR_RELATION NWPR ON NWPR.PRPR_ID=PRPR.PRPR_ID AND SYSDATE BETWEEN NWPR.NWPR_EFF_DT AND NWPR.NWPR_TERM_DT
JOIN FACETS.CMC_NWST_NET_SET NWST ON NWST.NWNW_ID = NWPR.NWNW_ID AND NWST.NWPR_PFX=NWPR.NWPR_PFX AND SYSDATE BETWEEN NWST.NWST_EFF_DT AND NWST.NWST_TERM_DT
JOIN FACETS.CMC_CSPI_CS_PLAN CSPI ON CSPI.NWST_PFX = NWST.NWST_PFX AND SYSDATE BETWEEN CSPI.CSPI_EFF_DT AND CSPI.CSPI_TERM_DT
JOIN FACETS.CMC_MEPE_PRCS_ELIG MEPE ON MEPE.CSPI_ID = CSPI.CSPI_ID AND MEPE.CSCS_ID = CSPI.CSCS_ID AND MEPE.CSPD_CAT = CSPI.CSPD_CAT AND MEPE.PDPD_ID=CSPI.PDPD_ID AND MEPE.GRGR_CK=CSPI.GRGR_CK AND SYSDATE BETWEEN MEPE.MEPE_EFF_DT AND MEPE.MEPE_TERM_DT
JOIN FACETS.CMC_MEME_MEMBER MEME ON MEME.MEME_CK = MEPE.MEME_CK AND MEME.GRGR_CK = MEPE.GRGR_CK
JOIN FACETS.CMC_SBSB_SUBSC SBSB ON SBSB.SBSB_CK = MEME.MEME_CK AND SBSB.GRGR_CK=MEME.GRGR_CK
WHERE SBSB.SBSB_ID IN(<Subscriber ID>)