SELECT DISTINCT 
PRPR.PRPR_ID AS "ID",
PRPR.PRPR_NAME AS "Name",
PRPR.PRPR_ENTITY AS "Provider Type",
PRPR.PRPR_NPI AS "NPI",
PRPR.MCTN_ID as "Tax ID" ,
PRPR.PRCF_MCTR_SPEC AS "Specialty Code",
MCTR.MCTR_DESC AS "Specialty Description"
FROM FACETS.CMC_PRPR_PROV PRPR 
JOIN FACETS.CMC_MCTR_CD_TRANS MCTR ON MCTR.MCTR_ENTITY='PRAC' AND MCTR.MCTR_TYPE='SPEC' AND MCTR.MCTR_VALUE = PRPR.PRCF_MCTR_SPEC
JOIN FACETS.CMC_PRAD_ADDRESS PRAD ON PRAD.PRAD_ID=PRPR.PRAD_ID